apiVersion: v1
kind: Service 
metadata: 
    name: my-node-port-ip-app
spec:
    type: NodePort     
    selector:
        app: ip-app
    ports: 
      - name: http 
        port: 30004
        targetPort: 8080
        nodePort: 30006 
        
        
Note:- Here provide the same lables which we have in the deployment.yml file.
spec:
    type: NodePort     
    selector:
        app: ip-app


Flow:-
Service is created
    No Pods yet → nothing happens
Deployment creates Pods
    Service automatically detects them ✅

👉 Service is dynamic, not static

It doesn’t store Pod IPs permanently
It updates automatically when:
        Pods are created
        Pods are deleted

Service Type → NodePort (external access)
Selector → connects Service to Pods
port → internal Service port
targetPort → container port
nodePort → external access port
